---
- hosts: default
  become: yes
  roles:
    - { role: ansible-role-logstash,
        logstash_elasticsearch_user: "user",
        logstash_elasticsearch_password: "pass",
        logstash_elasticsearch_hosts: ["192.168.0.1", "192.168.0.2", "192.168.0.3"] }